ApiBundle\Entity\Company:
    type: entity
    table: companies
    repositoryClass: ApiBundle\Entity\CompanyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
