ApiBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: ApiBundle\Entity\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        email:
            type: string
            length: 255
            column: email
        updatedOn:
            type: datetime
            nullable: true
        createdOn:
            type: datetime
            nullable: true

    lifecycleCallbacks:
        prePersist: [setCreatedOn]
        preUpdate: [setUpdatedOn]
