#api_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: ApiBundle:Default:index }

api_restul:
    type: rest
    prefix: /v1
    resource: "ApiBundle\Controller\RestfulController"
    name_prefix:  api_v1_ # naming collision