parameters:
    api.user.handler.class: ApiBundle\Handler\UserHandler
    api.user.class: ApiBundle\Entity\User

services:
    api.user.handler:
        class: %api.user.handler.class%
        arguments: [doctrine.orm.entity_manager, "%api.user.class%", form.factory]