parameters:
    api.user.handler.class: ApiBundle\Handler\UserHandler
    api.user.class: ApiBundle\Entity\User

services:
    api.user.handler:
        class: "%api.user.handler.class%"
        arguments: ["@=service('doctrine.orm.entity_manager')", "%api.user.class%", "@=service('form.factory')"]