api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

nmpolo_rest:
    resource: "@NmpoloRestBundle/Controller/"
    type:     annotation
    prefix:   /

nmpolo:
    type: rest
    resource: "@NmpoloRestBundle/Resources/config/routing.yml"
