#api:
#    resource: "@ApiBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type: annotation

rest_api:
    type: rest
    prefix: /api
    resource: "@ApiBundle/Resources/config/routing.yml"